services:

  rabbitmq:
    image: rabbitmq:3.11.20-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    ports:
      - 6379:6379

  pubsub:
    image: google/cloud-sdk:latest
    container_name: pubsub-emulator
    command: >
      gcloud beta emulators pubsub start
      --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    environment:
      PUBSUB_PROJECT_ID: test-project

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"

  elasticmq:
    image: softwaremill/elasticmq
    container_name: elasticmq
    ports:
      - "9324:9324"       # REST port
    environment:
      - JAVA_OPTS=-Dconfig.file=/opt/elasticmq.conf

